# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  google:
    map:
      api:
        # Your google api key: https://developers.google.com/maps/documentation/javascript/examples/map-simple#all
        # If api is wrong or null user only see the init location of the map, user can't search
        key: ""
